dist: trusty
language: ruby
rvm:
- 2.3.1
gemfile:
  - Gemfile
branches:
  only:
    - master
    - develop
before_script:
  - bundle install
script:
  - foodcritic .
  - rubocop
  - bundle exec rspec
env:
  - CHEF_VERSION=master
  - CHEF_VERSION=12.18.31
  - CHEF_VERSION=12.17.44
