dist: trusty
language: ruby
rvm:
- 2.3.1
gemfile:
  - Gemfile
branches:
  only:
    - master
    - develop
before_script:
  - bundle install
script:
  - bundle exec rspec
env:
  - CHEF_VERSION=master
  - CHEF_VERSION=12.18.31
  - CHEF_VERSION=12.17.44
  - CHEF_VERSION=12.16.42
  - CHEF_VERSION=12.15.19
  - CHEF_VERSION=12.14.89
  - CHEF_VERSION=12.13.37
  - CHEF_VERSION=12.12.15
  - CHEF_VERSION=12.11.18
  - CHEF_VERSION=12.10.24
  - CHEF_VERSION=12.9.41
  - CHEF_VERSION=12.8.1
  - CHEF_VERSION=12.7.2
  - CHEF_VERSION=12.6.0
