name 'mongodb_users'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mongodb_users'
long_description 'Installs/Configures mongodb_users'
version '0.1.0'
issues_url 'https://github.com/chriswessells/mongodb_users/issues'
source_url 'https://github.com/chriswessells/mongodb_users'
