name 'mongodb_users'
maintainer 'Chris Wessells'
maintainer_email 'cwessells@silvervue.com'
license 'all_rights'
description 'Installs/Configures mongodb_users'
long_description 'Installs/Configures mongodb_users'
version '0.1.0'
issues_url 'https://github.com/chriswessells/mongodb_users/issues'
source_url 'https://github.com/chriswessells/mongodb_users'

gem 'mongo'
